### ISSUE TITLE
Question - does the header photo depict what we do?

### ISSUE THREAD

**Issue by richsilv** [tableflip/tableflip-www#24]
Yes, it's community and it makes us look like we know what we're doing.

However, it seems to be appealing to people who are looking for somebody to teach a room full of kids to code, rather than people who are looking for a site/app to be built.

**Comment by olizilla** [comment]
I agree, it'd be good to get something more appropriate up there. Anyone got any alternatives? What does tableflip look like?

**Comment by olizilla** [comment]
There are lots of header photos now. PRs to add new photos or header fancies, welcome!
